version: 2
updates:
  - package-ecosystem: "pub" # See documentation for possible values
    directory: "/src" # Location of package manifests
    schedule:
      interval: "daily"
    groups:
      flutter-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      actions-dependencies:
        patterns:
          - "*"